version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  ApplicationStop:
    - location: appfiles/kill_container.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: appfiles/start_container.sh
      timeout: 10
      runas: root